2008-01-02  Alvaro Lopez Ortega  <alvaro@sun.com>
       * glib/ghash.c (g_hash_table_replace, g_hash_table_insert): These
       functions prototype defines its output as void, and therefore they
       should not return any value. This patch fixes a compilation error:
       the "return" clauses were incompatible with the functions prototype.


git-svn-id: http://svn.gnome.org/svn/glib/trunk@6230 5bbd4a9e-d125-0410-bf1d-f987e7eefc80